language: python
sudo: false
arch: 
  - ppc64le
  - amd64
matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
  exclude:
    - python: pypy3
branches:
  only:
    - master

before_install:
  - pip install -U setuptools pip wheel

install:
  - python -V
  - pip install .

script:
  - ./tests.py
  - python mypy_run.py

